[2023-11-29 00:07:53,842] utils.py->check_file_field line:100 Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

[2023-11-29 00:11:27,392] __init__.py->global_exception line:17 86d52dbb-fda6-4f1b-990a-999263152659 Exception: the JSON object must be str, bytes or bytearray, not method
[2023-11-29 00:12:19,498] __init__.py->global_exception line:17 f584317f-a257-4942-9526-cec61ad09d9e Exception: 'str' object has no attribute 'name'
[2023-11-29 00:12:40,408] __init__.py->global_exception line:17 cb22821e-129f-4e91-bd17-da228ad9a564 Exception: 'str' object has no attribute 'name'
[2023-11-29 00:15:00,275] __init__.py->global_exception line:17 03c2706a-735d-420d-94d3-fd79487f40d8 Exception: 'str' object has no attribute 'name'
[2023-11-29 00:17:22,949] __init__.py->global_exception line:17 8b505315-ef90-4411-99d6-5b9efc3caa75 Exception: can only concatenate str (not "Morsel") to str
[2023-11-29 00:18:40,523] __init__.py->global_exception line:17 3a8a7bd1-766f-4b2d-a961-7780b1047872 Exception: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https://errors.pydantic.dev/2.5/v/model_attributes_type'}

[2023-11-29 00:19:07,694] __init__.py->global_exception line:17 b9070006-b2e5-4531-8686-06bca9fef9ca Exception: 'SimpleCookie' object is not callable
[2023-11-29 00:19:22,780] __init__.py->global_exception line:17 a9c0fcd5-1b03-45cd-a4cb-454c994fcb7f Exception: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https://errors.pydantic.dev/2.5/v/model_attributes_type'}

[2023-11-29 00:19:36,319] __init__.py->global_exception line:17 7b5929f1-a814-4fdf-b736-47a005466189 Exception: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https://errors.pydantic.dev/2.5/v/model_attributes_type'}

[2023-11-29 00:21:32,909] __init__.py->global_exception line:17 df4e3d1a-04eb-4ffe-b8fd-179373c40593 Exception: bcrypt: no backends available -- recommend you install one (e.g. 'pip install bcrypt')
[2023-11-29 00:22:44,938] __init__.py->global_exception line:17 726fbe13-10e8-483e-bfa5-ca133c42e48d Exception: bcrypt: no backends available -- recommend you install one (e.g. 'pip install bcrypt')
[2023-11-29 00:23:57,364] __init__.py->global_exception line:17 8f203d38-ea55-45d8-ba36-c543cbc9319e Exception: can only concatenate str (not "float") to str
[2023-11-29 00:24:46,551] __init__.py->global_exception line:17 35e405a2-10d0-4eff-8d3f-508bd67bf2f3 Exception: can only concatenate str (not "float") to str
[2023-11-29 00:25:10,672] __init__.py->global_exception line:17 cc55fe29-0bf9-45df-b0df-1491ace67d33 Exception: (pymysql.err.IntegrityError) (1048, "Column 'user_id' cannot be null")
[SQL: INSERT INTO table_account (user_id, username, phone, uid, cookie, deleted) VALUES (%s, %s, %s, %s, %s, %s)]
[parameters: (None, None, '18960973410', '195747597', 'JSESSIONID=0CC9CC42D412295C0D6854015C32543F;lv=1;fid=906;_uid=195747597;uf=14b6b1b3f40d8f90db6d67377e77eed9a80418e7372a1bc87ff3c7e9fb7452ba1a68fc9bca ... (665 characters truncated) ... NotJDaUOpnVu3ooc;xxtenc=409ce8855c193d2c6a90417a93563238;DSSTASH_LOG=C_38-UN_472-US_195747597-T_1701188711383;route=2751c02f853f6479988f0b3d8a5cb9ce;', 0)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2023-11-29 00:26:11,974] __init__.py->global_exception line:17 2c657689-9594-4190-a33a-9acf63b3347d Exception: (pymysql.err.IntegrityError) (1048, "Column 'user_id' cannot be null")
[SQL: INSERT INTO table_account (user_id, username, phone, uid, cookie, deleted) VALUES (%s, %s, %s, %s, %s, %s)]
[parameters: (None, None, '18960973410', '195747597', 'JSESSIONID=6D2BAC68E2B1D0B165887CA29193522A;lv=1;fid=906;_uid=195747597;uf=14b6b1b3f40d8f90db6d67377e77eed9a80418e7372a1bc87ff3c7e9fb7452ba1a68fc9bca ... (663 characters truncated) ... SUjpTkqa6299xBlo;xxtenc=409ce8855c193d2c6a90417a93563238;DSSTASH_LOG=C_38-UN_472-US_195747597-T_1701188772681;route=2751c02f853f6479988f0b3d8a5cb9ce;', 0)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2023-11-29 00:27:24,036] __init__.py->global_exception line:17 1a764b4c-2487-445b-8ae1-20932d6e353c Exception: (pymysql.err.IntegrityError) (1048, "Column 'username' cannot be null")
[SQL: INSERT INTO table_account (user_id, username, phone, uid, cookie, deleted) VALUES (%s, %s, %s, %s, %s, %s)]
[parameters: (2, None, '18960973410', '195747597', 'JSESSIONID=E2722ED6611BF0F90B3DC7C08B4A8300;lv=1;fid=906;_uid=195747597;uf=14b6b1b3f40d8f90db6d67377e77eed9a80418e7372a1bc87ff3c7e9fb7452ba1a68fc9bca ... (667 characters truncated) ... cAVq1yRNpNXO65i8;xxtenc=409ce8855c193d2c6a90417a93563238;DSSTASH_LOG=C_38-UN_472-US_195747597-T_1701188844752;route=2751c02f853f6479988f0b3d8a5cb9ce;', 0)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2023-11-29 00:28:08,484] __init__.py->global_exception line:17 36465f5b-cb7d-421d-82fb-7c45222feddd Exception: (pymysql.err.DataError) (1406, "Data too long for column 'cookie' at row 1")
[SQL: INSERT INTO table_account (user_id, username, phone, uid, cookie, deleted) VALUES (%s, %s, %s, %s, %s, %s)]
[parameters: (2, None, '18960973410', '195747597', 'JSESSIONID=779123775B1D11312F2AAD08BC5073D2;lv=1;fid=906;_uid=195747597;uf=14b6b1b3f40d8f90db6d67377e77eed9a80418e7372a1bc87ff3c7e9fb7452ba1a68fc9bca ... (661 characters truncated) ... oc0CZ5i4QwP_NBeQ;xxtenc=409ce8855c193d2c6a90417a93563238;DSSTASH_LOG=C_38-UN_472-US_195747597-T_1701188889202;route=3a66e47c0ac92560e5c67cd5e1803201;', 0)]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
[2023-11-29 00:34:41,712] __init__.py->global_exception line:17 3bb51b6f-36a2-4cab-9ab4-b0e9a9940963 Exception: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`chaoxing`.`table_account`, CONSTRAINT `table_account_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `table_user` (`user_id`))')
[SQL: INSERT INTO table_account (user_id, username, phone, uid, cookie, deleted) VALUES (%s, %s, %s, %s, %s, %s)]
[parameters: (2, None, '18960973410', '195747597', 'JSESSIONID=F4AED4EF8D1E278770B721D19B59A028;lv=1;fid=906;_uid=195747597;uf=14b6b1b3f40d8f90db6d67377e77eed9a80418e7372a1bc87ff3c7e9fb7452ba1a68fc9bca ... (665 characters truncated) ... Fes4is18aXJZq6J8;xxtenc=409ce8855c193d2c6a90417a93563238;DSSTASH_LOG=C_38-UN_472-US_195747597-T_1701189282442;route=26e346b982eea47de2f6652532e77800;', 0)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2023-11-29 00:37:11,948] __init__.py->global_exception line:17 9f41a50a-44c7-4a37-a1ce-6defcba227ca Exception: 1 validation error for AccountOut
username
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
